#Somebody created a blob document in a storage account to hold a secret. Only the secret disappeared from the blob storage [$null].
#Could you retrieve the secret from Azure and restore it?

#Azure costs for these resources per hour ~0 dollar. 

trigger: none

pool:
  vmImage: 'ubuntu-latest'


steps:

- task: AzureCLI@2
  displayName: Create lab setup
  inputs:
    azureSubscription: <YourAzureConnectionName>
    scriptType: pscore
    scriptLocation: inlineScript
    inlineScript: |
        Write-Host "##[section]Create restore Blob storage"
        $resourcegroup = "RestoreBloBSecret"
        az group create --name $resourcegroup --location "east-us"
        $storagename = -join ((97..122) | Get-Random -Count 12 | % {[char]$_})
        New-Item -Path . -Name "testfile1.txt" -ItemType "file" -Value "This is a text string with secret code UI873632rt."
        New-Item -Path . -Name "testfile2.txt" -ItemType "file" -Value "This is a text string with secret code [$null]."
        az storage account create -n $storagename -g $resourcegroup --sku Standard_LRS
        az storage blob service-properties delete-policy update --days-retained 7  --account-name $storagename --enable true
        az storage container create --name "cloudsandboxes" --account-name $storagename
        az storage blob upload --container-name "cloudsandboxes" --account-name $storagename --file testfile1.txt --name secret.txt
        Start-Sleep -Second 3
        az storage blob upload --container-name "cloudsandboxes" --account-name $storagename --file testfile2.txt --name secret.txt
        Start-Sleep -Second 3
        az storage blob upload --container-name "cloudsandboxes" --account-name $storagename --file testfile2.txt --name secret.txt
        Start-Sleep -Second 3
        az storage blob upload --container-name "cloudsandboxes" --account-name $storagename --file testfile2.txt --name secret.txt
        
