#cloud-config
write_files:

-   path: /home/start-app.sh
    permissions: 0777
    owner: root
    content: |
        #!/bin/bash
        set -e
        sudo iptables -P OUTPUT ACCEPT
        iptables -A OUTPUT -o eth0 -p tcp --sport 22 -m state --state ESTABLISHED -j ACCEPT
        sudo iptables -A OUTPUT -p udp --dport 80 -j ACCEPT 
        sudo iptables -A OUTPUT -p udp --dport 443 -j ACCEPT 
        cd /home
        echo 'sudo iptables -A OUTPUT -p tcp --dport 80 -j DROP' >> initialize-security.sh 
        echo 'sudo iptables -A OUTPUT -p tcp --dport 443 -j DROP' >> initialize-security.sh 
        sudo chmod 755 initialize-security.sh 
        cd /etc/systemd/system 
        echo '[Service]' >> security.service 
        echo 'ExecStart= /bin/bash /home/initialize-security.sh' >> security.service 
        echo '[Install]' >> security.service 
        echo 'WantedBy=multi-user.target' >> security.service 
        sudo chmod 644 /etc/systemd/system/security.service 
        sudo systemctl enable security.service 
        systemctl daemon-reload 
        sudo systemctl restart security.service"

runcmd:
    - bash /home/start-app.sh
